name: move files
on: [push]
jobs:
  move:
    name: Move
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: move file with args
      uses: Flywheel-Energy/move-files@master
      with:
        source: "tests/a.txt"
        target: "tests/files/"
        flags: "-v"
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.0.1